# Generated by Django 5.0.6 on 2026-07-06 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intake_data', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TriageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likely_causes', models.JSONField(default=list)),
                ('urgency_level', models.CharField(choices=[('home_care', 'Home care'), ('see_doctor_soon', 'See a doctor soon'), ('emergency', 'Emergency')], max_length=20)),
                ('next_steps', models.TextField(blank=True)),
                ('ai_provider_used', models.CharField(blank=True, max_length=30)),
                ('is_mock', models.BooleanField(default=False)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='triage.triagesession')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
