# Generated by Django 5.0.6 on 2026-07-06 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse')], max_length=10)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=10)),
                ('voice_id', models.CharField(blank=True, help_text='ElevenLabs voice id. Leave blank until you have a real ElevenLabs account and pick a voice.', max_length=100)),
                ('avatar_image_url', models.URLField(blank=True, help_text='A hosted portrait photo used as the D-ID source image. Leave blank to fall back to the illustrated avatar.')),
                ('tagline', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AvatarSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_sessions', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='avatar_sessions.persona')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvatarTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_text', models.TextField()),
                ('assistant_text', models.TextField(blank=True)),
                ('tts_audio_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video_status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='skipped', max_length=15)),
                ('provider_job_id', models.CharField(blank=True, max_length=200)),
                ('text_provider_used', models.CharField(blank=True, max_length=30)),
                ('tts_provider_used', models.CharField(blank=True, max_length=30)),
                ('avatar_provider_used', models.CharField(blank=True, max_length=30)),
                ('is_mock', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='avatar_sessions.avatarsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
