# Generated by Django 5.0.6 on 2026-07-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('drug_class', models.CharField(blank=True, max_length=200)),
                ('adult_dosing', models.TextField(blank=True)),
                ('pediatric_dosing', models.TextField(blank=True)),
                ('how_to_take', models.TextField(blank=True)),
                ('food_alcohol_interactions', models.TextField(blank=True)),
                ('common_side_effects', models.TextField(blank=True)),
                ('serious_side_effects', models.TextField(blank=True)),
                ('missed_dose_guidance', models.TextField(blank=True)),
                ('interaction_warnings', models.JSONField(blank=True, default=list)),
                ('is_seeded', models.BooleanField(default=False)),
                ('generated_as_mock', models.BooleanField(default=False, help_text="True if this entry's content was produced by a mock AI provider (no key configured) rather than a real model.")),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
