# Generated by Django 5.0.6 on 2026-07-06 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_health_content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelAdvisoryQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_type', models.CharField(choices=[('cold', 'Cold or snowy'), ('hot_desert', 'Hot or desert'), ('beach_tropical', 'Beach or tropical'), ('cruise', 'Cruise'), ('forest_jungle', 'Forest or jungle'), ('high_altitude', 'Mountain or high-altitude'), ('urban_city', 'Urban or city')], max_length=20)),
                ('destination_name', models.CharField(blank=True, max_length=150)),
                ('advice', models.TextField(blank=True)),
                ('ai_provider_used', models.CharField(blank=True, max_length=30)),
                ('is_mock', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_advisory_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
