# Generated by Django 5.0.6 on 2026-07-06 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderLinkAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('nhs', 'NHS'), ('medicaid', 'Medicaid')], max_length=10)),
                ('status', models.CharField(choices=[('not_connected', 'Not connected'), ('pending_consent', 'Pending consent'), ('connected', 'Connected')], default='not_connected', max_length=20)),
                ('consent_scopes', models.JSONField(blank=True, default=list)),
                ('mock_mode', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='MockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('record_type', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('record_date', models.DateField()),
                ('link_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='integrations.providerlinkaccount')),
            ],
            options={
                'ordering': ['-record_date'],
            },
        ),
        migrations.CreateModel(
            name='MockAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('clinician_name', models.CharField(blank=True, max_length=150)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=10)),
                ('link_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='integrations.providerlinkaccount')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
    ]
