# Generated by Django 5.0.6 on 2026-07-18 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField()),
                ('is_read', models.BooleanField(default=False)),
                ('link_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='integrations.providerlinkaccount')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
