# Generated by Django 5.0.6 on 2026-07-06 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LifestyleAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answers', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifestyle_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LifestyleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField(blank=True)),
                ('strengths', models.JSONField(default=list)),
                ('improvement_areas', models.JSONField(default=list)),
                ('suggestions', models.JSONField(default=list)),
                ('ai_provider_used', models.CharField(blank=True, max_length=30)),
                ('is_mock', models.BooleanField(default=False)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='lifestyle.lifestyleassessment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
