# Generated by Django 5.0.6 on 2026-07-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('clinical', 'Clinical'), ('wellbeing', 'Wellbeing & beauty')], default='clinical', max_length=15)),
                ('overview', models.TextField()),
                ('history', models.TextField(blank=True)),
                ('severity_mortality_context', models.TextField(blank=True)),
                ('treatment_evolution', models.TextField(blank=True)),
                ('current_outlook', models.TextField(blank=True)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'disease entries',
                'ordering': ['name'],
            },
        ),
    ]
