# Generated by Django 5.0.6 on 2026-07-06 20:26

import apps.media_analysis.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.media_analysis.models.upload_path)),
                ('kind', models.CharField(choices=[('skin_image', 'Skin photo'), ('xray', 'X-ray'), ('lab_report', 'Lab report'), ('prescription', 'Prescription'), ('discharge_summary', 'Discharge summary')], max_length=20)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField(blank=True)),
                ('structured_findings', models.JSONField(default=list)),
                ('confidence', models.CharField(blank=True, max_length=20)),
                ('flagged_for_clinician', models.BooleanField(default=False)),
                ('ai_provider_used', models.CharField(blank=True, max_length=30)),
                ('is_mock', models.BooleanField(default=False)),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='media_analysis.uploadedmedia')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
