# Generated by Django 5.0.6 on 2026-07-06 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeditationGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('tone', models.CharField(choices=[('funny', 'Funny'), ('moderate', 'Moderate'), ('serious', 'Serious')], max_length=10)),
                ('avatar_image_url', models.URLField(blank=True)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('voice_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['tone', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MeditationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_type', models.CharField(choices=[('breathing', 'Breathing & posture'), ('poem', 'Poem'), ('motivation', 'Motivation'), ('hardship', 'Talk it out')], max_length=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=10)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='meditation.meditationguide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meditation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeditationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_text', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('is_mock', models.BooleanField(default=False)),
                ('text_provider_used', models.CharField(blank=True, max_length=30)),
                ('tts_provider_used', models.CharField(blank=True, max_length=30)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='meditation.meditationsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
